### ISSUE TITLE
Interested in participating in other open source projects?

### ISSUE THREAD

**Issue by ZiadJ** [RyanRizzo96/QuadrupedRobot_DeepRN#1]
Hi Ryan, I'm working on a few projects that are meant to help us implement a new economic system not revolving around money and for that we need to secure out basic needs first through automated methods. I'm mostly focusing on food and shelter right now and I thought you might want to get involved somehow. If that's the case then feel free to let me know.

**Comment by RyanRizzo96** [comment]
Hi, can you email me the details on ieeerizzo@gmail.com please? Thanks
